// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate with: pnpm db:types
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      achievements: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          icon_key: string
          icon_url: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config: Json
          target_count: number
          reward_coins: number
          reward_item_id: string | null
          is_secret: boolean
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          icon_key?: string
          icon_url?: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          reward_coins?: number
          reward_item_id?: string | null
          is_secret?: boolean
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          icon_key?: string
          icon_url?: string | null
          requirement_type?: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          reward_coins?: number
          reward_item_id?: string | null
          is_secret?: boolean
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "achievements_reward_item_id_fkey"
            columns: ["reward_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          }
        ]
      }
      activity_log: {
        Row: {
          id: number
          user_id: string
          kind: string
          title: string
          metadata: Json
          created_at: string
        }
        Insert: {
          user_id: string
          kind: string
          title: string
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          kind?: string
          title?: string
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      admin_users: {
        Row: {
          user_id: string
          role: Database["public"]["Enums"]["admin_role"]
          created_by: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          role?: Database["public"]["Enums"]["admin_role"]
          created_by?: string | null
          created_at?: string
        }
        Update: {
          user_id?: string
          role?: Database["public"]["Enums"]["admin_role"]
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_users_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_users_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      adoption_attempts: {
        Row: {
          id: number
          user_id: string | null
          ip_hash: string | null
          result: string
          code_id: string | null
          attempted_at: string
        }
        Insert: {
          user_id?: string | null
          ip_hash?: string | null
          result: string
          code_id?: string | null
          attempted_at?: string
        }
        Update: {
          id?: number
          user_id?: string | null
          ip_hash?: string | null
          result?: string
          code_id?: string | null
          attempted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "adoption_attempts_code_id_fkey"
            columns: ["code_id"]
            isOneToOne: false
            referencedRelation: "adoption_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adoption_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      adoption_codes: {
        Row: {
          id: string
          code_hash: string
          code_hint: string
          batch_id: string | null
          sku_id: string
          status: Database["public"]["Enums"]["code_status"]
          redeemed_by: string | null
          redeemed_at: string | null
          disabled_at: string | null
          disabled_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          code_hash: string
          code_hint: string
          batch_id?: string | null
          sku_id: string
          status?: Database["public"]["Enums"]["code_status"]
          redeemed_by?: string | null
          redeemed_at?: string | null
          disabled_at?: string | null
          disabled_reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          code_hash?: string
          code_hint?: string
          batch_id?: string | null
          sku_id?: string
          status?: Database["public"]["Enums"]["code_status"]
          redeemed_by?: string | null
          redeemed_at?: string | null
          disabled_at?: string | null
          disabled_reason?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "adoption_codes_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "code_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adoption_codes_redeemed_by_fkey"
            columns: ["redeemed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adoption_codes_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "product_skus"
            referencedColumns: ["id"]
          }
        ]
      }
      audit_logs: {
        Row: {
          id: number
          actor_user_id: string | null
          action: string
          target_table: string | null
          target_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          actor_user_id?: string | null
          action: string
          target_table?: string | null
          target_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: number
          actor_user_id?: string | null
          action?: string
          target_table?: string | null
          target_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      character_variants: {
        Row: {
          id: string
          character_id: string
          slug: string
          name: string
          description: string | null
          rarity_slug: string
          image_url: string | null
          thumbnail_url: string | null
          sprite_url: string | null
          placeholder_color: string
          status: Database["public"]["Enums"]["content_status"]
          release_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          character_id: string
          slug: string
          name: string
          description?: string | null
          rarity_slug: string
          image_url?: string | null
          thumbnail_url?: string | null
          sprite_url?: string | null
          placeholder_color?: string
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          character_id?: string
          slug?: string
          name?: string
          description?: string | null
          rarity_slug?: string
          image_url?: string | null
          thumbnail_url?: string | null
          sprite_url?: string | null
          placeholder_color?: string
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "character_variants_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "character_variants_rarity_slug_fkey"
            columns: ["rarity_slug"]
            isOneToOne: false
            referencedRelation: "rarities"
            referencedColumns: ["slug"]
          }
        ]
      }
      characters: {
        Row: {
          id: string
          slug: string
          name: string
          species: string
          personality_key: string
          personality_label: string
          tagline: string | null
          description: string | null
          catchphrase: string | null
          favorite_food: string | null
          favorite_activity: string | null
          trait: string | null
          home_location_id: string | null
          rarity_slug: string
          image_url: string | null
          thumbnail_url: string | null
          sprite_url: string | null
          placeholder_color: string
          placeholder_shape: string
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          release_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          species?: string
          personality_key: string
          personality_label: string
          tagline?: string | null
          description?: string | null
          catchphrase?: string | null
          favorite_food?: string | null
          favorite_activity?: string | null
          trait?: string | null
          home_location_id?: string | null
          rarity_slug: string
          image_url?: string | null
          thumbnail_url?: string | null
          sprite_url?: string | null
          placeholder_color?: string
          placeholder_shape?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          species?: string
          personality_key?: string
          personality_label?: string
          tagline?: string | null
          description?: string | null
          catchphrase?: string | null
          favorite_food?: string | null
          favorite_activity?: string | null
          trait?: string | null
          home_location_id?: string | null
          rarity_slug?: string
          image_url?: string | null
          thumbnail_url?: string | null
          sprite_url?: string | null
          placeholder_color?: string
          placeholder_shape?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "characters_home_location_id_fkey"
            columns: ["home_location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "characters_rarity_slug_fkey"
            columns: ["rarity_slug"]
            isOneToOne: false
            referencedRelation: "rarities"
            referencedColumns: ["slug"]
          }
        ]
      }
      code_batches: {
        Row: {
          id: string
          name: string
          sku_id: string
          quantity: number
          notes: string | null
          created_by: string | null
          exported_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          sku_id: string
          quantity: number
          notes?: string | null
          created_by?: string | null
          exported_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          sku_id?: string
          quantity?: number
          notes?: string | null
          created_by?: string | null
          exported_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "code_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "code_batches_sku_id_fkey"
            columns: ["sku_id"]
            isOneToOne: false
            referencedRelation: "product_skus"
            referencedColumns: ["id"]
          }
        ]
      }
      currencies: {
        Row: {
          slug: string
          name: string
          icon: string
          created_at: string
        }
        Insert: {
          slug: string
          name: string
          icon?: string
          created_at?: string
        }
        Update: {
          slug?: string
          name?: string
          icon?: string
          created_at?: string
        }
        Relationships: []
      }
      currency_transactions: {
        Row: {
          id: number
          user_id: string
          currency_slug: string
          amount: number
          balance_after: number
          source: Database["public"]["Enums"]["acquisition_source"]
          reference_type: string | null
          reference_id: string | null
          note: string | null
          idempotency_key: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          currency_slug: string
          amount: number
          balance_after: number
          source: Database["public"]["Enums"]["acquisition_source"]
          reference_type?: string | null
          reference_id?: string | null
          note?: string | null
          idempotency_key?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          currency_slug?: string
          amount?: number
          balance_after?: number
          source?: Database["public"]["Enums"]["acquisition_source"]
          reference_type?: string | null
          reference_id?: string | null
          note?: string | null
          idempotency_key?: string | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "currency_transactions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "currency_transactions_currency_slug_fkey"
            columns: ["currency_slug"]
            isOneToOne: false
            referencedRelation: "currencies"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "currency_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      daily_rewards: {
        Row: {
          day_index: number
          label: string
          reward_coins: number
          reward_item_id: string | null
          status: Database["public"]["Enums"]["content_status"]
        }
        Insert: {
          day_index: number
          label: string
          reward_coins?: number
          reward_item_id?: string | null
          status?: Database["public"]["Enums"]["content_status"]
        }
        Update: {
          day_index?: number
          label?: string
          reward_coins?: number
          reward_item_id?: string | null
          status?: Database["public"]["Enums"]["content_status"]
        }
        Relationships: [
          {
            foreignKeyName: "daily_rewards_reward_item_id_fkey"
            columns: ["reward_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          }
        ]
      }
      events: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          banner_url: string | null
          starts_at: string
          ends_at: string
          config: Json
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          banner_url?: string | null
          starts_at: string
          ends_at: string
          config?: Json
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          banner_url?: string | null
          starts_at?: string
          ends_at?: string
          config?: Json
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      game_scores: {
        Row: {
          id: number
          user_id: string
          game_id: string
          score: number
          coins_awarded: number
          duration_ms: number | null
          played_on: string
          created_at: string
        }
        Insert: {
          user_id: string
          game_id: string
          score: number
          coins_awarded?: number
          duration_ms?: number | null
          played_on?: string
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          game_id?: string
          score?: number
          coins_awarded?: number
          duration_ms?: number | null
          played_on?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_scores_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      games: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string | null
          description: string | null
          thumbnail_url: string | null
          placeholder_color: string
          location_id: string | null
          coins_per_point: number
          max_coins_per_play: number
          max_coins_per_day: number
          min_play_seconds: number
          supports_touch: boolean
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline?: string | null
          description?: string | null
          thumbnail_url?: string | null
          placeholder_color?: string
          location_id?: string | null
          coins_per_point?: number
          max_coins_per_play?: number
          max_coins_per_day?: number
          min_play_seconds?: number
          supports_touch?: boolean
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string | null
          description?: string | null
          thumbnail_url?: string | null
          placeholder_color?: string
          location_id?: string | null
          coins_per_point?: number
          max_coins_per_play?: number
          max_coins_per_day?: number
          min_play_seconds?: number
          supports_touch?: boolean
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "games_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          }
        ]
      }
      item_categories: {
        Row: {
          slug: string
          name: string
          sort_order: number
          is_background: boolean
        }
        Insert: {
          slug: string
          name: string
          sort_order?: number
          is_background?: boolean
        }
        Update: {
          slug?: string
          name?: string
          sort_order?: number
          is_background?: boolean
        }
        Relationships: []
      }
      items: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          category_slug: string
          rarity_slug: string
          image_url: string | null
          placeholder_color: string
          coin_price: number | null
          coin_value: number
          is_shop_available: boolean
          is_limited_edition: boolean
          is_tradeable: boolean
          unlock_method: Database["public"]["Enums"]["acquisition_source"]
          series_id: string | null
          collection_tag: string | null
          width_units: number
          height_units: number
          max_per_user: number | null
          shop_starts_at: string | null
          shop_ends_at: string | null
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          category_slug: string
          rarity_slug?: string
          image_url?: string | null
          placeholder_color?: string
          coin_price?: number | null
          coin_value?: number
          is_shop_available?: boolean
          is_limited_edition?: boolean
          is_tradeable?: boolean
          unlock_method?: Database["public"]["Enums"]["acquisition_source"]
          series_id?: string | null
          collection_tag?: string | null
          width_units?: number
          height_units?: number
          max_per_user?: number | null
          shop_starts_at?: string | null
          shop_ends_at?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          category_slug?: string
          rarity_slug?: string
          image_url?: string | null
          placeholder_color?: string
          coin_price?: number | null
          coin_value?: number
          is_shop_available?: boolean
          is_limited_edition?: boolean
          is_tradeable?: boolean
          unlock_method?: Database["public"]["Enums"]["acquisition_source"]
          series_id?: string | null
          collection_tag?: string | null
          width_units?: number
          height_units?: number
          max_per_user?: number | null
          shop_starts_at?: string | null
          shop_ends_at?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "items_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "item_categories"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "items_rarity_slug_fkey"
            columns: ["rarity_slug"]
            isOneToOne: false
            referencedRelation: "rarities"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "items_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "series"
            referencedColumns: ["id"]
          }
        ]
      }
      location_unlocks: {
        Row: {
          id: string
          location_id: string
          tier: number
          tier_label: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config: Json
          target_count: number
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          location_id: string
          tier?: number
          tier_label?: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          location_id?: string
          tier?: number
          tier_label?: string | null
          requirement_type?: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          sort_order?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "location_unlocks_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          }
        ]
      }
      locations: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string | null
          description: string | null
          image_url: string | null
          map_x: number
          map_y: number
          series_id: string | null
          link_type: Database["public"]["Enums"]["location_link_type"]
          link_target: string | null
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline?: string | null
          description?: string | null
          image_url?: string | null
          map_x?: number
          map_y?: number
          series_id?: string | null
          link_type?: Database["public"]["Enums"]["location_link_type"]
          link_target?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string | null
          description?: string | null
          image_url?: string | null
          map_x?: number
          map_y?: number
          series_id?: string | null
          link_type?: Database["public"]["Enums"]["location_link_type"]
          link_target?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "locations_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "series"
            referencedColumns: ["id"]
          }
        ]
      }
      product_skus: {
        Row: {
          id: string
          sku: string
          name: string
          series_id: string | null
          character_id: string
          variant_id: string | null
          shopify_product_id: string | null
          shopify_variant_id: string | null
          purchase_url: string | null
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sku: string
          name: string
          series_id?: string | null
          character_id: string
          variant_id?: string | null
          shopify_product_id?: string | null
          shopify_variant_id?: string | null
          purchase_url?: string | null
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sku?: string
          name?: string
          series_id?: string | null
          character_id?: string
          variant_id?: string | null
          shopify_product_id?: string | null
          shopify_variant_id?: string | null
          purchase_url?: string | null
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_skus_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_skus_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "series"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_skus_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "character_variants"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_key: string
          status: Database["public"]["Enums"]["account_status"]
          suspended_reason: string | null
          onboarding_completed_at: string | null
          last_seen_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string
          avatar_key?: string
          status?: Database["public"]["Enums"]["account_status"]
          suspended_reason?: string | null
          onboarding_completed_at?: string | null
          last_seen_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_key?: string
          status?: Database["public"]["Enums"]["account_status"]
          suspended_reason?: string | null
          onboarding_completed_at?: string | null
          last_seen_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      quests: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          flavor_text: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config: Json
          target_count: number
          reward_coins: number
          reward_item_id: string | null
          series_id: string | null
          event_id: string | null
          giver_character_id: string | null
          repeat_interval: Database["public"]["Enums"]["repeat_interval"]
          starts_at: string | null
          ends_at: string | null
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          flavor_text?: string | null
          requirement_type: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          reward_coins?: number
          reward_item_id?: string | null
          series_id?: string | null
          event_id?: string | null
          giver_character_id?: string | null
          repeat_interval?: Database["public"]["Enums"]["repeat_interval"]
          starts_at?: string | null
          ends_at?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          flavor_text?: string | null
          requirement_type?: Database["public"]["Enums"]["requirement_type"]
          requirement_config?: Json
          target_count?: number
          reward_coins?: number
          reward_item_id?: string | null
          series_id?: string | null
          event_id?: string | null
          giver_character_id?: string | null
          repeat_interval?: Database["public"]["Enums"]["repeat_interval"]
          starts_at?: string | null
          ends_at?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quests_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quests_giver_character_id_fkey"
            columns: ["giver_character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quests_reward_item_id_fkey"
            columns: ["reward_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quests_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "series"
            referencedColumns: ["id"]
          }
        ]
      }
      rarities: {
        Row: {
          slug: string
          name: string
          description: string | null
          sort_order: number
          color_hex: string
          odds_label: string | null
          created_at: string
        }
        Insert: {
          slug: string
          name: string
          description?: string | null
          sort_order?: number
          color_hex?: string
          odds_label?: string | null
          created_at?: string
        }
        Update: {
          slug?: string
          name?: string
          description?: string | null
          sort_order?: number
          color_hex?: string
          odds_label?: string | null
          created_at?: string
        }
        Relationships: []
      }
      room_items: {
        Row: {
          id: string
          room_id: string
          item_id: string
          grid_x: number
          grid_y: number
          z_index: number
          flipped: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          room_id: string
          item_id: string
          grid_x?: number
          grid_y?: number
          z_index?: number
          flipped?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          item_id?: string
          grid_x?: number
          grid_y?: number
          z_index?: number
          flipped?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_items_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_items_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          }
        ]
      }
      rooms: {
        Row: {
          id: string
          user_id: string
          name: string
          is_primary: boolean
          background_item_id: string | null
          active_mibbi_id: string | null
          grid_columns: number
          grid_rows: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name?: string
          is_primary?: boolean
          background_item_id?: string | null
          active_mibbi_id?: string | null
          grid_columns?: number
          grid_rows?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          is_primary?: boolean
          background_item_id?: string | null
          active_mibbi_id?: string | null
          grid_columns?: number
          grid_rows?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rooms_active_mibbi_id_fkey"
            columns: ["active_mibbi_id"]
            isOneToOne: false
            referencedRelation: "user_mibbis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rooms_background_item_id_fkey"
            columns: ["background_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rooms_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      series: {
        Row: {
          id: string
          slug: string
          code: string
          name: string
          tagline: string | null
          description: string | null
          cover_image_url: string | null
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          release_date: string | null
          completion_reward_item_id: string | null
          completion_unlock_location_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          code: string
          name: string
          tagline?: string | null
          description?: string | null
          cover_image_url?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          completion_reward_item_id?: string | null
          completion_unlock_location_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          code?: string
          name?: string
          tagline?: string | null
          description?: string | null
          cover_image_url?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          release_date?: string | null
          completion_reward_item_id?: string | null
          completion_unlock_location_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "series_completion_reward_item_fk"
            columns: ["completion_reward_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "series_completion_unlock_location_fk"
            columns: ["completion_unlock_location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          }
        ]
      }
      series_characters: {
        Row: {
          series_id: string
          character_id: string
          sort_order: number
          required_for_completion: boolean
        }
        Insert: {
          series_id: string
          character_id: string
          sort_order?: number
          required_for_completion?: boolean
        }
        Update: {
          series_id?: string
          character_id?: string
          sort_order?: number
          required_for_completion?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "series_characters_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "series_characters_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "series"
            referencedColumns: ["id"]
          }
        ]
      }
      user_achievements: {
        Row: {
          user_id: string
          achievement_id: string
          earned_at: string
        }
        Insert: {
          user_id: string
          achievement_id: string
          earned_at?: string
        }
        Update: {
          user_id?: string
          achievement_id?: string
          earned_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_achievements_achievement_id_fkey"
            columns: ["achievement_id"]
            isOneToOne: false
            referencedRelation: "achievements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_achievements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_balances: {
        Row: {
          user_id: string
          currency_slug: string
          balance: number
          lifetime_earned: number
          lifetime_spent: number
          updated_at: string
        }
        Insert: {
          user_id: string
          currency_slug: string
          balance?: number
          lifetime_earned?: number
          lifetime_spent?: number
          updated_at?: string
        }
        Update: {
          user_id?: string
          currency_slug?: string
          balance?: number
          lifetime_earned?: number
          lifetime_spent?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_balances_currency_slug_fkey"
            columns: ["currency_slug"]
            isOneToOne: false
            referencedRelation: "currencies"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "user_balances_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_daily_claims: {
        Row: {
          id: number
          user_id: string
          claimed_on: string
          streak: number
          day_index: number
          reward_coins: number
          reward_item_id: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          claimed_on: string
          streak: number
          day_index: number
          reward_coins?: number
          reward_item_id?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          claimed_on?: string
          streak?: number
          day_index?: number
          reward_coins?: number
          reward_item_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_daily_claims_day_index_fkey"
            columns: ["day_index"]
            isOneToOne: false
            referencedRelation: "daily_rewards"
            referencedColumns: ["day_index"]
          },
          {
            foreignKeyName: "user_daily_claims_reward_item_id_fkey"
            columns: ["reward_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_daily_claims_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_inventory: {
        Row: {
          id: string
          user_id: string
          item_id: string
          quantity: number
          acquired_via: Database["public"]["Enums"]["acquisition_source"]
          first_acquired_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          item_id: string
          quantity?: number
          acquired_via: Database["public"]["Enums"]["acquisition_source"]
          first_acquired_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          item_id?: string
          quantity?: number
          acquired_via?: Database["public"]["Enums"]["acquisition_source"]
          first_acquired_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_inventory_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_inventory_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_location_visits: {
        Row: {
          user_id: string
          location_id: string
          first_visited_at: string
          last_visited_at: string
          visit_count: number
        }
        Insert: {
          user_id: string
          location_id: string
          first_visited_at?: string
          last_visited_at?: string
          visit_count?: number
        }
        Update: {
          user_id?: string
          location_id?: string
          first_visited_at?: string
          last_visited_at?: string
          visit_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "user_location_visits_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_location_visits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_mibbis: {
        Row: {
          id: string
          user_id: string
          character_id: string
          variant_id: string | null
          adoption_code_id: string | null
          nickname: string | null
          is_favorite: boolean
          mood: string
          last_fed_at: string | null
          last_played_at: string | null
          adopted_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          character_id: string
          variant_id?: string | null
          adoption_code_id?: string | null
          nickname?: string | null
          is_favorite?: boolean
          mood?: string
          last_fed_at?: string | null
          last_played_at?: string | null
          adopted_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          character_id?: string
          variant_id?: string | null
          adoption_code_id?: string | null
          nickname?: string | null
          is_favorite?: boolean
          mood?: string
          last_fed_at?: string | null
          last_played_at?: string | null
          adopted_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_mibbis_adoption_code_id_fkey"
            columns: ["adoption_code_id"]
            isOneToOne: true
            referencedRelation: "adoption_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_mibbis_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_mibbis_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_mibbis_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "character_variants"
            referencedColumns: ["id"]
          }
        ]
      }
      user_quests: {
        Row: {
          id: string
          user_id: string
          quest_id: string
          period_key: string
          progress: number
          status: Database["public"]["Enums"]["user_quest_status"]
          completed_at: string | null
          claimed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          quest_id: string
          period_key?: string
          progress?: number
          status?: Database["public"]["Enums"]["user_quest_status"]
          completed_at?: string | null
          claimed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          quest_id?: string
          period_key?: string
          progress?: number
          status?: Database["public"]["Enums"]["user_quest_status"]
          completed_at?: string | null
          claimed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_quests_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_quests_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      user_series_progress: {
        Row: {
          user_id: string | null
          series_id: string | null
          series_slug: string | null
          owned_required: number | null
          total_required: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      apply_currency_transaction: {
        Args: {
          p_user_id: string
          p_amount: number
          p_source: Database["public"]["Enums"]["acquisition_source"]
          p_reference_type?: string
          p_reference_id?: string
          p_note?: string
          p_idempotency_key?: string
          p_currency_slug?: string
        }
        Returns: number
      }
      grant_item: {
        Args: {
          p_user_id: string
          p_item_id: string
          p_quantity: number
          p_source: Database["public"]["Enums"]["acquisition_source"]
        }
        Returns: undefined
      }
      has_admin_role: {
        Args: {
          p_role: Database["public"]["Enums"]["admin_role"]
        }
        Returns: boolean
      }
      is_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      purchase_item: {
        Args: {
          p_item_id: string
          p_quantity?: number
        }
        Returns: Json
      }
      redeem_adoption_code: {
        Args: {
          p_code_hash: string
          p_nickname?: string
          p_ip_hash?: string
        }
        Returns: Json
      }
      write_audit_log: {
        Args: {
          p_action: string
          p_target_table: string
          p_target_id: string
          p_metadata?: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      account_status: "active" | "suspended"
      acquisition_source: "purchase" | "quest" | "adoption" | "series_completion" | "event" | "achievement" | "daily_reward" | "game" | "promo" | "admin" | "starter"
      admin_role: "owner" | "admin" | "support"
      code_status: "active" | "redeemed" | "disabled"
      content_status: "draft" | "active" | "archived"
      location_link_type: "none" | "game" | "shop" | "quest" | "character" | "event" | "page"
      repeat_interval: "none" | "daily" | "weekly"
      requirement_type: "adopt_count" | "adopt_character" | "adopt_rarity" | "series_owned_count" | "series_complete" | "play_game_count" | "game_score" | "earn_coins" | "spend_coins" | "room_items_placed" | "login_days" | "login_streak" | "visit_locations" | "visit_location" | "feed_mibbi" | "own_items" | "custom"
      user_quest_status: "active" | "completed" | "claimed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
